### ISSUE TITLE
А где взять вёрстку?

### ISSUE THREAD

**Issue by Negossia** [iserdmi/card-info#12]
Привет. Чё-то не нашёл описания, как это чудо встроить на страницу.

**Comment by MadMed677** [comment]
@Negossia Привет. А в доке этого и нету. Это библиотека помогает взять все данные по номеру карты, то как ты будешь это имплементировать в код, уже на тебе.

**Comment by iserdmi** [comment]
Привет, @Negossia ! @MadMed677 всё правильно говорит. Хотя в папке с демо есть пример: https://github.com/iserdmi/card-info/tree/master/demo

**Comment by igor-pgmt** [comment]
Ясно, понятно, спасибо.
