### ISSUE TITLE
А как использовать в реальной жизни?

### ISSUE THREAD

**Issue by socketpair** [iserdmi/card-info#2]
Ведь номера карт вводятся на убер-секурных сайтах платёжных систем. Получается, эта либа нужна только тем кто разрабатывает свою систему? Не плохо, конечно, но...

**Comment by iserdmi** [comment]
Есть сервисы, позволяющие создавать формы оплаты прямо на сайте.

Я подключал [Stripe](https://stripe.com/) своему клиенту, это пожалуй самый популярный в мире сервис, но он недоступен для предпринимателей из России. Карточки может откуда хочешь принять, но фирма должна быть зарегистрирована [в одной из этих стран](https://stripe.com/global)

Есть наш отечественный сервис [CloudPayments](https://cloudpayments.ru/) с ним не работал, но вроде как функционал со страйпом схожий.
