### ISSUE TITLE
Отсутствует изображение карт Яндекс.Деньги

### ISSUE THREAD

**Issue by arsensokolov** [iserdmi/card-info#3]
Проверено на номерах 5106 21

**Comment by iserdmi** [comment]
Добавлю карты яндекс денег вместе со следующим обновлением. Хочу ещё логотипы мастеркарда и маэстро перерисовать, сейчас старые логотипы.

**Comment by MadMed677** [comment]
@iserdmi если нужно, могу предоставить SVG/PNG иконки Яндекс.Денег

**Comment by iserdmi** [comment]
Подумав, я решил, что логотип яндекс денег сейчас добавлять не стану. Дело в том, что когда я создавал этот плагин, я направлял письма в яндекс с просьбой дать мне разрешение взять логотипы банков с их сайта. На что они мне ответили довольно холодным отказам, и вообще дали понять, что не рады идеи создания такого плагина, а второе письмо и вовсе проигнорировали. Возможно, я параноик, но не хочу размещать их логотип, чтобы они потом вдруг не смогли мне предъявить претензий касательно прав на их средства идентификации.
