### ISSUE TITLE
Пересечение регулярных выражений

### ISSUE THREAD

**Issue by windx-foobar** [iserdmi/card-info#33]
Обратите внимание на паттерны mir и master-card
У выражений идет пересечение

mastercard
/^(51|52|53|54|55|**22**|23|24|25|26|27)/

mir
/^(**22**)/

Насколько я понял, утилита выдает неизвестную платежную систему, если есть пересечение.
![2022-04-15_16-49](https://user-images.githubusercontent.com/80086846/163579057-3370c80e-15b1-444b-bad7-a7055f29d202.png)

**Comment by andreygmc** [comment]
Для мира правильнее:
`pattern: /^(2200|2201|2202|2203|2204)\d*$/`

**Comment by iserdmi** [comment]
Спасибо за наводку! Поправил в https://github.com/sdandteam/binking/tree/2.0.13
