### ISSUE TITLE
Мошенники

### ISSUE THREAD

**Issue by maxfactor** [iserdmi/card-info#35]
Обратите внимание, что Ваш проект активно используют мошенники:
https://sberbank.id-5875415.ru/assets/sberbank/js/card-info.js

**Comment by iserdmi** [comment]
Здравствуйте. Когда мы видим, что мошенники используют АПИ, тогда мы блокируем доступ с их сайта. Эти мошенники используют чистый JS, то есть они просто скопировали код и используют, мы никак не можем ничего с этим сделать, кроме как закрыть проект (да и то не поможет, так как данные уже в сети)

**Comment by maxfactor** [comment]
Здравствуйте! Спасибо большое за ответ!
Печально(
