### ISSUE TITLE
Пересечение паттернов у бренда VISA и MAESTRO

### ISSUE THREAD

**Issue by SprayDev** [iserdmi/card-info#36]
Если вводить номер карты начинающий с "49".
VISA: /^4/
MAESTRO: /^(49|50|56|59|63|67)/
то плагин не сможет определить бренд и в дальнейшем ставит максимальную длинну номера карты 12.
И получаются случаи когда у номера карты нету никаких ошибок, по типу CARD_NUMBER_LUHN, то плагин говорит, что все ОК и у номера карты нету ошибок.

**Comment by iserdmi** [comment]
Спасибо за наводку! Поправил в https://github.com/sdandteam/binking/tree/2.0.13
