### ISSUE TITLE
English documentation

### ISSUE THREAD

**Issue by frankcortes** [iserdmi/card-info#6]
Hi @iserdmi, your library looks pretty cool IMHO, but it is a bit inaccessible for most of the community due to the (I think) russian documentation. Wouldn't it be interesting to translate it to English? :)

**Comment by mistermjtek** [comment]
+1 
Right now, using google translate to read it in English. It'd also be great to add support for banks in other countries other than Russia. :world_map:

**Comment by iserdmi** [comment]
Hi! Of course I'm planning to translate documentation to english. Also I have plan to add another countries. But right now there is russian banks only here, so only russian documentation. Previously it was looking logically for me. But now...

Why are you need this library, guys? :–) Seriously, I can't understand. I expect that this library will be useful for those who creates card forms in that countries which listed in library. Right now there is russian banks only. So, are you created bank card form for your russian customer? Or you wan't add this library to your project, and then waiting when your countries will be added to library? I need to understand who uses this library and why, to make this library better. And how did you know about this library? I only add [one article to my blog](http://srdm.io/%D0%B7%D0%B0%D0%BC%D0%B5%D1%82%D0%BA%D0%B8/card-info) and to russian IT resource cold [«habrahabr».](https://habrahabr.ru/post/324738/) So I don't understand how another world could get information about this library.

I'm not good in english, excuse me. And it is one of reasons why documentation not translated to english right now.

**Comment by frankcortes** [comment]
Hi @iserdmi , oh... you said a lot of things there. Let's try to answer one by one:
 - Maybe you don't promote your library outside of the Russian dev ecosystem, but this is not the only way to do your repo more visible. [Your repo is appearing like "trending" in the GitHub website,](https://github.com/trending/javascript) probably because you had a good impact in the Russian community and your repo has been starred a lot, which is nice 😄 
- Don't be afraid of your level of English to translate the documentation. It's fine because you can expand your library to other people who doesn't know your language. If you want, you could do a draft of the English translation in a PR and maybe another guys can be help you. I would like to help, but I don't know anything about Russian 😢. [A tag like 'help wanted'](https://github.com/marionettejs/backbone.marionette/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) in your PR or this issue could be a good way to ask for helping.
- In my particular case, I'm not using this library for now, but If you expand the library could be more useful for people who are working with no-Russian banks and you could have more collaborators who can help you to improve and maintain the code.  

Anyway, sorry for my long response, those are my suggestions, and I hope they can be useful for you :)

**Comment by iserdmi** [comment]
@frankcortes , thanks for explanation! Everything you say is very useful for me. I will add english readme and english demo page as soon as possible.

**Comment by iserdmi** [comment]
I have translate README.md by Google translate and make some fixes. So I think, now it has really a lot mistakes. I will be very grateful to those who help fix all mistakes. Also I ask to inform me, when the documentation will come in due form, as I myself can not understand it.

**Comment by iserdmi** [comment]
Also I add link to [demo-page](http://srdm.io/demo/card-info), which also has a lot of mistakes, but it placed on my own site which not stored on GitHub.
