### ISSUE TITLE
Заменить список BIN на Regex

### ISSUE THREAD

**Issue by igoradamenko** [iserdmi/card-info#9]
Привет, клёвая библиотека :-)

Подскажи, а зачем писать весь список БИНов? Может есть смысл вместо них, например, написать  регулярку или что-то подобное? Это же сильно сократит итоговый размер.

Или я чего-то не уловил? 🐨

**Comment by iserdmi** [comment]
Привет. Список префиксов для каждого банка слишком разрозненный, возможно с помощью переписания в регулярное выражение и получится что-то сократить но не так существенно, как кажется. И регулярка будет иметь примерно такой вид: `/^(406372|416132|...)\d*/` и вообще всё станет заморочно, а сейчас всё очень прозрачно.

Плюс благодаря полному перечислению бинов мне удаётся оптимизровать сам процесс поиска банка. Все информация о банках хранятся в объекте:
```
{
  'ru-bank-alias-1': { ... },
  'ru-bank-alias-2': { ... },
  ...
}
```

Все префиксы хранятся в объекте
```
{
  '123456': 'ru-bank-alias-1',
  '234567': 'ru-bank-alias-1',
  '123456': 'ru-bank-alias-2',
  '234567': 'ru-bank-alias-2',
}
```

И соответственно чтобы найти информацию о банке мне нужно совершить только 2 операции, проверить наличие ключа в объекте с префиксами, а потом по его значению (при наличии) найти значение в банках. Если будет регулярка, то мне придётся проверять номер карты по регулярке для каждого из банков, а делать это нужно после каждого введённого символа. Можно конечно оптимизировать, но мне кажется всё и сейчас работает хорошо. А вес самой библиотеки не такой критичный, чтобы стараться его оптимизировать.

**Comment by igoradamenko** [comment]
Окей, понял. Спасибо за ответ! 🐨
